### PR TITLE
Support auto-scrolling

### PR DESCRIPTION
**Pull request by mattiacitterio**
If you set max-height to your menu you will probably see vertical scrollbar. This adjust scroll-top while moving up and down with arrows.

### CODE REVIEW

**Comment by hrj** [comment]
Confirming that this works fine with `Firefox 38.0` and `Chromium 43`

**Comment by dhaeb** [comment]
I would really like to see this be merged into the project. This is a so common usecase.
Cheers

**Comment by dhaeb** [comment]
Well after some more investigation it seems that there is a more lightweight way, to achieve this:
- Set the number of items in your suggetions list (items parameter of bootstrap3-typeahead) to the number of total results, that can be scrolled for (so I set it to 20, but one can only see the first ~10 results, for the others you need to scroll down)
- add the following css:
```css
ul.typeahead {
    height: auto;
    max-height: 300px;
    overflow-x: hidden;
}
 ```
- enjoy scrolling, for me, it looks like this:
scrollbar-ldb

**Comment by dphizler** [comment]
clicking on the scrollbar makes results disappear, this is counter intuitive

**Comment by dhaeb** [comment]
Interesstingly enough, this happens only sometimes:
http://kdi-student.de:9000/#/http://dbpedia.org/sparql/subject/http://dbpedia.org/resource/DBpedia
But I really don't know why.

**Comment by bassjobsen** [comment]
@dhaeb  should i close this PR cause the CSS does the same?

**Comment by dphizler** [comment]
Do whatever you want, I beg to differ, clicking on the sidebar of the dropdown shouldn't close it. Really that's just logical.

**Comment by bassjobsen** [comment]
@dphizler does the PR fix your issue? and the CSS not?

**Comment by dmoebius** [comment]
I think this issue should be reopened. The CSS fixes only the problem with the menu showing a vertical scrollbar. The PR fixes a different problem: adjusting scroll-top while moving up and down in the menu with arrow keys. Please accept the PR.

**Comment by marcmarcet** [comment]
I agree, this should be accepted. Currently is not possible to scroll using key down/key up when there is a max-height set.

**Comment by Maczuga** [comment]
Bump, issue still exists! PR fixes it.

**Pull request closed without merging**
