### PR TITLE
Improve for bootstrap 4 (anew)

### PR DESCRIPTION
**Pull request by ErwSim**
Based on pull request https://github.com/bassjobsen/Bootstrap-3-Typeahead/pull/322

### CODE REVIEW

**Comment by bassjobsen** [comment]
Hii @ErwSim 

Thank you very much. I wonder if your fixes are backwards compatible too?

Best regards,

Bass

**Comment by kristofdegrave** [comment]
Maybe it's an idea to have the ability to choose the bootstrap 4 template, bootstrap 3 template or some thing custom. This way it stays backwards compatible.

Concerning my PR some issues I have get  also fixed with this, but I would implement them differently 

For example


```
 -        prev = this.$menu.find('li').last();
 +        prev = this.$menu.find('button').last();
```

Maybe it is an idea to replace this by the tag name of the item:
`prev = this.$menu.find($(this.options.item).prop("tagName")).last();`

Maybe for performance reasons this better gets cached.

If you want I can look for making this PR if you like the idea.

**Comment by bassjobsen** [comment]
hi @kristofdegrave how should one choose the templates?
Using the tagname seems a good idea.

**Comment by kristofdegrave** [comment]
I was thinking in the following direction
```
{
    theme: "bootstrap3"
    themes: {
       bootstrap3: {
             menu: '<ul class="typeahead dropdown-menu" role="listbox"></ul>',
             item: '<li><a class="dropdown-item" href="#" role="option"></a></li>',
             itemContentSelector: "a",
             headerHtml: '<li class="dropdown-header"></li>',
             headerDivider: '<li class="divider" role="separator"></li>'
       }     
       bootstrap4: {
             menu: "<div class=\"typeahead dropdown-menu\" role=\"listbox\"></div>",
             item: "<button class=\"dropdown-item\" role=\"option\"></button>",
             itemContentSelector: ".dropdown-item",
             headerHtml: "<h6 class=\"dropdown-header\"></h6>",
             headerDivider: "<div class=\"dropdown-divider\"></div>"
       } 
   },
}
```

so the default theme should be bootstrap3, you can choose bootstrap 4 if you want.

When setting the templates I would suggest the following logic:
1. check if 1 of the 5 properties (menu, item, ...) is provided use that.
2. in case that the above is undefined, use the provided theme
3. if the above should be undefined (= unvalid theme) fallback on bootstrap3

**Pull request closed without merging**
