### PR TITLE
Supporting `dropup` and `dropdown-menu-right` styles

### PR DESCRIPTION
**Pull request by rlamorea**
Addresses: https://github.com/bassjobsen/Bootstrap-3-Typeahead/issues/224

If the parent has `dropup` style, the menu will appear above the input rather than below.
If the `menu` element (defined in the `menu` option) includes the `dropdown-menu-right` style,
the menu will align to the right of the input rather than the left.

This was codes as a "do no harm" approach, so it only changes the `top` and `left` styles in the `show` method if these styles are detected.  However, it seems like there is a good chance that removing these styles entirely and letting Bootstrap handle menu placement should work.  I didn't have time to exhaustively test that.

(Note this was tested against Bootstrap 4)

This also includes a jshint pass on the code to clean it up according to those guidelines.

### CODE REVIEW

**Comment by bassjobsen** [comment]
thank you very much. I merge it now, cause it works does not break anything. Indeed we should also test against Bootstrap 3

**Comment by rlamorea** [comment]
Hmmm, `bower install bootstrap3-typeahead` still seems to install an older version.

Both the `bower.json` and `package.json` files show version as 4.0.0 even though it is installed as:
`bootstrap3-typeahead#4.0.1` in the command line output and placed into my bower.json as:
`"bootstrap3-typeahead": "^4.0.1"`

Odd.

**Comment by bassjobsen** [comment]
can i fix this?

**Comment by rlamorea** [comment]
Not sure.  I didn't update the version in `bower.json` or `package.json`.  Maybe if they get updated the changes will get picked up?  Though I'm still not sure why if I look at the code installed by bower, it shows version 4.0.0 in those files.  Don't know quite enough about bower yet.

**Comment by rlamorea** [comment]
FWIW:

     $ bower update --force bootstrap3-typeahead
     bower bootstrap3-typeahead#^4.0.1          resolve https://github.com/bassjobsen/Bootstrap-3-Typeahead.git#^4.0.1
     bower bootstrap3-typeahead#^4.0.1         checkout 4.0.1
     bower bootstrap3-typeahead#^4.0.1         mismatch Version declared in the json (v4.0.0) is different than the resolved one (4.0.1)
     bower bootstrap3-typeahead#^4.0.1         resolved https://github.com/bassjobsen/Bootstrap-3-Typeahead.git#4.0.1
     bower bootstrap3-typeahead#^4.0.1          install bootstrap3-typeahead#4.0.1

**Comment by bassjobsen** [comment]
okay thanks we'll wait a while

**Pull request merged**
